/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/column/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Column(props) {
  const { nodes, materials } = useGLTF('./models/column/model.glb ')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Column_Round1.geometry} material={materials.Marble} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('./models/column/model.glb ')
