/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/eye/model.glb 
Author: Tomentos (https://sketchfab.com/tomentos)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/brown-eyeball-5f1cdc109b8f447691dac47062de388b
Title: Brown eyeball
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Eye(props) {
  const { nodes, materials } = useGLTF('/models/eye/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Eyeball} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Iris} position={[0, 1.71, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 0.5, 1]} />
    </group>
  )
}

useGLTF.preload('')
