/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/grass/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Grass(props) {
  const { nodes, materials } = useGLTF('./models/grass/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat9} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat10} />
    </group>
  )
}

useGLTF.preload('./models/grass/model.glb')
