/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/head/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Head(props) {
  const { nodes, materials } = useGLTF('./models/head/model.glb ')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.texture_pbr_v128.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/head/model.glb ')
