/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/head3/model.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Head3(props) {
  const { nodes, materials } = useGLTF("/models/head3/model.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.model.geometry}
        material={materials.CustomMaterial}
        rotation={[Math.PI / 2, 0, 0]}
      />
        {/* <mesh geometry={nodes.Cube.geometry} material={materials.Material} /> */}
    </group>
  );
}

useGLTF.preload("/models/head3/model.glb");
