/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/multiIsland/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Island(props) {
  const { nodes, materials } = useGLTF('./models/multiIsland/model.glb ')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group1651290667.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group615116044.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group694142508.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1810082506.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1493570185.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1035743550.geometry} material={materials.mat9} />
      <mesh geometry={nodes.group1061609037.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group575109798.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1441309711.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group1094615483.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group125708411.geometry} material={materials.mat20} />
      <mesh geometry={nodes.group698118262.geometry} material={materials.mat20} />
    </group>
  )
}

useGLTF.preload('./models/multiIsland/model.glb ')
