/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/statue/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Statue(props) {
  const { nodes, materials } = useGLTF('./models/statue/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node2.geometry} material={materials.x1} />
    </group>
  )
}

useGLTF.preload('./models/statue/model.glb ')
