/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/sunflower/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Sunflower(props) {
  const { nodes, materials } = useGLTF('./models/sunflower/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sunflower.geometry} material={materials.None} />
    </group>
  )
}

useGLTF.preload('./models/sunflower/model.glb')
